version: "3"

services:
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
